# Generated by Django 5.2.17 on 2026-09-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("gestionnaire", "Gestionnaire"),
                    ("comptable", "Comptable"),
                    ("magasinier", "Magasinier"),
                    ("caissier", "Caissier"),
                    ("livreur", "Livreur"),
                    ("vendeur", "Vendeur"),
                ],
                default="vendeur",
                max_length=20,
            ),
        ),
    ]
