# Generated by Django 5.2.17 on 2026-10-07 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_role"),
        ("ventes_clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="client_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Si ce compte utilisateur correspond à un client existant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_accounts",
                to="ventes_clients.client",
                verbose_name="Profil client lié",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(
                default=True,
                help_text="Les clients doivent être approuvés par un admin avant de pouvoir accéder à leur espace",
                verbose_name="Approuvé par un administrateur",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("gestionnaire", "Gestionnaire"),
                    ("comptable", "Comptable"),
                    ("magasinier", "Magasinier"),
                    ("caissier", "Caissier"),
                    ("livreur", "Livreur"),
                    ("vendeur", "Vendeur"),
                    ("client", "Client"),
                ],
                default="vendeur",
                max_length=20,
            ),
        ),
    ]
