# Generated by Django 5.2.17 on 2026-10-05 20:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produits_stocks", "0002_alter_product_barcode_alter_product_unit_and_more"),
        ("tresorerie", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Taxe",
                "verbose_name_plural": "Taxes",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code client"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom / Raison sociale"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("particulier", "Particulier"),
                            ("entreprise", "Entreprise"),
                            ("revendeur", "Revendeur"),
                            ("grossiste", "Grossiste"),
                        ],
                        default="particulier",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("bloque", "Bloqué"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Avoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avoir_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro d'avoir"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("refund", "Remboursement"),
                            ("return", "Retour de marchandise"),
                            ("discount", "Remise / Geste commercial"),
                            ("error", "Erreur de facturation"),
                        ],
                        default="refund",
                        max_length=20,
                        verbose_name="Type d'avoir",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant total",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Motif de l'avoir (retour, remboursement, etc.)",
                        verbose_name="Raison",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "restore_stock",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si le stock a été restauré suite à cet avoir",
                        verbose_name="Stock restauré",
                    ),
                ),
                (
                    "stock_restored_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date de restauration du stock",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avoirs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avoirs",
                        to="ventes_clients.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avoir",
                "verbose_name_plural": "Avoirs",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ClientWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Solde disponible",
                    ),
                ),
                (
                    "total_deposits",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total des dépôts",
                    ),
                ),
                (
                    "total_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total utilisé",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Wallet actif"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="ventes_clients.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Porte-monnaie client",
                "verbose_name_plural": "Porte-monnaie clients",
            },
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "devis_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° Devis"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Nom client"),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone client"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email client"
                    ),
                ),
                (
                    "client_address",
                    models.TextField(blank=True, verbose_name="Adresse client"),
                ),
                (
                    "devis_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date devis"),
                ),
                ("valid_until", models.DateField(verbose_name="Valable jusqu'au")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Sous-total",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Pourcentage"), ("amount", "Montant")],
                        default="percentage",
                        max_length=20,
                        verbose_name="Type remise",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valeur remise",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Montant remise",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux TVA (%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Montant TVA",
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Frais de livraison",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("accepted", "Accepté"),
                            ("refused", "Refusé"),
                            ("expired", "Expiré"),
                            ("converted", "Converti en vente"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notes internes"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/devis/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "qr_code_data",
                    models.TextField(blank=True, verbose_name="Données QR Code"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date modification"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devis",
                        to="ventes_clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devis",
                        to="produits_stocks.warehouse",
                        verbose_name="Entrepôt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "ordering": ["-devis_date"],
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyée"),
                            ("paid", "Payée"),
                            ("overdue", "En retard"),
                            ("cancelled", "Annulée"),
                            ("partial", "Partiellement payée"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="qrcodes/invoices/"
                    ),
                ),
                ("qr_code_data", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="ventes_clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="LigneDevis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="ventes_clients.devis",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produits_stocks.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de devis",
                "verbose_name_plural": "Lignes de devis",
            },
        ),
        migrations.CreateModel(
            name="LigneVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Taux de TVA (%)",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Total ligne",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("detail", "Prix de détail"),
                            ("gros", "Prix de gros"),
                        ],
                        default="detail",
                        max_length=20,
                        verbose_name="Type de prix utilisé",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits_stocks.lot",
                        verbose_name="Lot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produits_stocks.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de vente",
                "verbose_name_plural": "Lignes de vente",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LigneAvoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Quantité retournée",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total ligne",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "avoir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="ventes_clients.avoir",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_avoir",
                        to="produits_stocks.product",
                    ),
                ),
                (
                    "ligne_vente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lignes_avoir",
                        to="ventes_clients.lignevente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'avoir",
                "verbose_name_plural": "Lignes d'avoir",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Espèces"),
                            ("card", "Carte bancaire"),
                            ("check", "Chèque"),
                            ("transfer", "Virement"),
                            ("mobile_money", "Mobile Money"),
                            ("credit", "Crédit"),
                            ("wallet", "Porte-monnaie électronique"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="qrcodes/payments/"
                    ),
                ),
                ("qr_code_data", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caisse_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_entrants",
                        to="tresorerie.caisse",
                        verbose_name="Caisse de destination",
                    ),
                ),
                (
                    "compte_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_entrants",
                        to="tresorerie.comptebancaire",
                        verbose_name="Compte bancaire de destination",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="ventes_clients.facture",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Remise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("percentage", "Pourcentage"),
                            ("amount", "Montant fixe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "min_purchase",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clients",
                    models.ManyToManyField(blank=True, to="ventes_clients.client"),
                ),
            ],
            options={
                "verbose_name": "Remise",
                "verbose_name_plural": "Remises",
            },
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("client_name", models.CharField(blank=True, max_length=200)),
                ("client_phone", models.CharField(blank=True, max_length=20)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("client_address", models.TextField(blank=True)),
                ("sale_date", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateTimeField(blank=True, null=True)),
                ("payment_due_date", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Pourcentage"), ("amount", "Montant")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("partial", "Paiement partiel"),
                            ("paid", "Payé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("delivery_method", models.CharField(blank=True, max_length=50)),
                ("delivery_address", models.TextField(blank=True, null=True)),
                ("delivery_status", models.CharField(default="pending", max_length=50)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("confirmed", "Confirmée"),
                            ("paid", "Payée"),
                            ("delivered", "Livrée"),
                            ("cancelled", "Annulée"),
                            ("returned", "Retournée"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="qrcodes/sales/"
                    ),
                ),
                ("qr_code_data", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="ventes_clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventes",
                        to="produits_stocks.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vente",
                "verbose_name_plural": "Ventes",
                "ordering": ["-sale_date"],
            },
        ),
        migrations.AddField(
            model_name="lignevente",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="ventes_clients.vente",
                verbose_name="Vente",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="ventes_clients.vente",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis_source",
                to="ventes_clients.vente",
            ),
        ),
        migrations.AddField(
            model_name="avoir",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avoirs",
                to="ventes_clients.vente",
                verbose_name="Vente associée",
            ),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("credit", "Crédit"), ("debit", "Débit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("deposit", "Dépôt en espèces"),
                            ("payment", "Paiement facture"),
                            ("avoir", "Avoir commercial"),
                            ("refund", "Remboursement"),
                            ("transfer", "Transfert"),
                            ("adjustment", "Ajustement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Solde après transaction",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="ventes_clients.clientwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction wallet",
                "verbose_name_plural": "Transactions wallet",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="avoir",
            index=models.Index(
                fields=["avoir_number"], name="ventes_clie_avoir_n_232d91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="avoir",
            index=models.Index(
                fields=["client", "-date"], name="ventes_clie_client__ad7733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="avoir",
            index=models.Index(fields=["type"], name="ventes_clie_type_df10a7_idx"),
        ),
        migrations.AddIndex(
            model_name="avoir",
            index=models.Index(fields=["sale"], name="ventes_clie_sale_id_28f010_idx"),
        ),
    ]
